const ROLE = ["ADMIN", "USER", "EMPLOYEE"];
const ADMINS = [
  {
    id: 0,
    username: "kiendd",
    password: "kiendeptrai",
    fullName: "Đặng Đình Kiên",
    about: "Có khả năng làm việc được dưới áp lực công việc lớn, chăm chỉ, cần cù, sáng tạo, nỗ lực cống hiến hết mình",
    company: "DDK Solutions Corporation",
    job: "Administrator",
    country: "Việt Nam",
    address: "Hà Nội",
    phone: "098773862087738620",
    email: "kiendd@gmail.com",
    avatar: "",
    gender: "Male",
    isADM: true,
    role: ROLE[0],
  },
  {
    id: 1,
    username: "huylee",
    password: "huydeptrai",
    fullName: "Lê Quốc Huy",
    about: "Có khả năng làm việc được dưới áp lực công việc lớn, chăm chỉ, cần cù, sáng tạo, nỗ lực cống hiến hết mình",
    company: "NT Solutions Corporation",
    job: "Administrator",
    country: "Hà Nội",
    address: "Vĩnh Phúc",
    phone: "0974747475",
    email: "huylee@gmail.com",
    avatar: "",
    gender: "Male",
    isADM: true,
    role: ROLE[0],
  },
  {
    id: 2,
    username: "khoavu",
    password: "khoadeptrai",
    fullName: "Vũ Cao Khoa",
    about: "Có khả năng làm việc được dưới áp lực công việc lớn, chăm chỉ, cần cù, sáng tạo, nỗ lực cống hiến hết mình",
    company: "NTQ Solutions Corporation",
    job: "Administrator",
    country: "Hà Nội",
    address: "Đống Đa",
    phone: "0974747476",
    email: "khoavu@gmail.com",
    avatar: "",
    gender: "Male",
    isADM: true,
    role: ROLE[0],
  },
  {
    id: 3,
    username: "quandt",
    password: "quandeptrai",
    fullName: "Nguyễn Văn Quân",
    about: "Có khả năng làm việc được dưới áp lực công việc lớn, chăm chỉ, cần cù, sáng tạo, nỗ lực cống hiến hết mình",
    company: "NTQ Solutions Corporation",
    job: "Employee",
    country: "Hà Nội",
    address: "Sơn Tây",
    phone: "0974747474",
    email: "quanna@gmail.com",
    avatar: "",
    gender: "Male",
    isADM: true,
    role: ROLE[2],
  },
  {
    id: 4,
    username: "hoalt",
    password: "hoaxinhgai",
    fullName: "Lê Thị Hòa",
    about: "Có khả năng làm việc được dưới áp lực công việc lớn, chăm chỉ, cần cù, sáng tạo, nỗ lực cống hiến hết mình",
    company: "NTQ Solutions Corporation",
    job: "Employee",
    country: "Hà Nội",
    address: "Vĩnh Phúc",
    phone: "0974747475",
    email: "quanvm@gmail.com",
    avatar: "",
    gender: "Female",
    isADM: true,
    role: ROLE[2],
  },

];

export default ADMINS;
